### ISSUE TITLE
What is the current state of this bundle?

### ISSUE THREAD

**Issue by devinivy** [ArturoBurela/ncc-ecommerce#1]
I started peeking through the codebase, and it seems like a huge amount of solid work has gone into this, but that there still may be some hard-coded configuration/values in there.  So, I'm curious what the current state of this bundle is, and if there are any plans to continue working on it.  Either way, thanks for all the great work—this is a fantastic example of a complex apostrophe bundle.

**Comment by ArturoBurela** [comment]
Hi, sorry for the late response. Indeed, there are still some issues and pending functionality, right now there are no plans to continue working on it at least until next year, although this project is not abandoned yet. I do plan to continue adding code in the future but right now I'm focusing on other projects. Thanks for your interest.
